import * as fs from 'fs';
import * as path from 'path';
import * as toml from '@iarna/toml';
import { build } from 'esbuild';

/**
 * Build script that bundles a Google Apps Script version of the tool.
 * - Reads geo-visibility-config.toml to pull prompts/settings (DRY)
 * - Generates src/gas/generated/config.ts with defaults
 * - Bundles src/gas/index.ts into dist/apps-script/ai-visibility.gs
 */

const root = process.cwd();
const configPath = path.join(root, 'geo-visibility-config.toml');
const generatedDir = path.join(root, 'src', 'gas', 'generated');
const outDir = path.join(root, 'dist', 'apps-script');

const ensureDir = (dir: string) => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
};

const loadTomlConfig = () => {
  if (!fs.existsSync(configPath)) {
    throw new Error(`Config file not found: ${configPath}`);
  }

  const raw = fs.readFileSync(configPath, 'utf-8');
  return toml.parse(raw) as {
    target_domain?: string;
    user_location?: string;
    language?: string;
    model_openai?: string;
    model_gemini?: string;
    prompts?: Record<string, string>;
  };
};

const writeGeneratedConfig = (parsed: ReturnType<typeof loadTomlConfig>) => {
  ensureDir(generatedDir);
  const file = path.join(generatedDir, 'config.ts');

  const prompts = parsed.prompts || {};

  const content = `// AUTO-GENERATED by scripts/build-gas.ts. Do not edit by hand.
export const DEFAULT_SETTINGS = {
  target_domain: ${JSON.stringify(parsed.target_domain || '')},
  user_location: ${JSON.stringify(parsed.user_location || '')},
  language: ${JSON.stringify(parsed.language || 'en')},
  model_openai: ${JSON.stringify(parsed.model_openai || 'gpt-5-mini')},
  model_gemini: ${JSON.stringify(parsed.model_gemini || 'gemini-2.5-flash')},
} as const;

export const DEFAULT_PROMPTS = ${JSON.stringify(prompts, null, 2)} as const;
`;

  fs.writeFileSync(file, content, 'utf-8');
  console.log(`✅ Wrote generated config: ${file}`);
};

const bundleGas = async () => {
  ensureDir(outDir);
  const outfile = path.join(outDir, 'ai-visibility.gs');

  await build({
    entryPoints: [path.join(root, 'src', 'gas', 'index.ts')],
    outfile,
    bundle: true,
    format: 'iife',
    target: 'es2020',
    platform: 'neutral',
    banner: {
      js: `// Generated for Google Apps Script. Source: src/gas | config: geo-visibility-config.toml\n// Paste this file into Apps Script editor (File > New > Script file).\n`,
    },
    banner: {
      js: `// Generated for Google Apps Script. Source: src/gas | config: geo-visibility-config.toml\n// Build time: ${new Date().toString()}\n// Paste this file into Apps Script editor (File > New > Script file).\n`,
    },
    footer: {
      js: [
        '// Expose named functions for the Apps Script UI picker',
        'var __onOpen = globalThis.onOpen;',
        'var __runNextBatch = globalThis.runNextBatch;',
        'var __showSetupSidebar = globalThis.showSetupSidebar;',
        'var __saveSetup = globalThis.saveSetup;',
        'var __requestCancel = globalThis.requestCancel;',
        'var __fullRestart = globalThis.fullRestart;',
        'function onOpen(){ return __onOpen && __onOpen(); }',
        'function runNextBatch(){ return __runNextBatch && __runNextBatch(); }',
        'function showSetupSidebar(){ return __showSetupSidebar && __showSetupSidebar(); }',
        'function saveSetup(form){ return __saveSetup && __saveSetup(form); }',
        'function requestCancel(){ return __requestCancel && __requestCancel(); }',
        'function fullRestart(){ return __fullRestart && __fullRestart(); }',
      ].join('\n'),
    },
  });

  console.log(`✅ Bundle created: ${outfile}`);
};

const run = async () => {
  const parsed = loadTomlConfig();
  writeGeneratedConfig(parsed);
  await bundleGas();
};

run().catch(err => {
  console.error('❌ build:gas failed', err);
  process.exit(1);
});
