/**
 * Build script for Cloudflare Workers deployment
 * - Reads geo-visibility-config.toml to pull prompts/settings (DRY)
 * - Generates workers/generated/prompts.ts with defaults
 * - Bundles workers/index.ts into dist/workers/index.js
 *
 * SAME PATTERN as build-gas.ts (DRY config injection)
 */

import * as fs from 'fs';
import * as path from 'path';
import * as toml from '@iarna/toml';
import { build } from 'esbuild';

const root = process.cwd();
const configPath = path.join(root, 'geo-visibility-config.toml');
const generatedDir = path.join(root, 'workers', 'generated');
const outDir = path.join(root, 'dist', 'workers');

const ensureDir = (dir: string) => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
};

/**
 * Load TOML config (SAME as build-gas.ts - DRY!)
 */
const loadTomlConfig = () => {
  if (!fs.existsSync(configPath)) {
    throw new Error(`Config file not found: ${configPath}`);
  }

  const raw = fs.readFileSync(configPath, 'utf-8');
  return toml.parse(raw) as {
    target_domain?: string;
    user_location?: string;
    language?: string;
    model_openai?: string;
    model_gemini?: string;
    prompts?: Record<string, string>;
  };
};

/**
 * Write generated prompts file (SAME PATTERN as build-gas.ts)
 */
const writeGeneratedPrompts = (parsed: ReturnType<typeof loadTomlConfig>) => {
  ensureDir(generatedDir);
  const file = path.join(generatedDir, 'prompts.ts');

  const prompts = parsed.prompts || {};

  const content = `// AUTO-GENERATED by scripts/build-worker.ts. Do not edit by hand.
// Generated from geo-visibility-config.toml (single source of truth)
export const DEFAULT_PROMPTS = ${JSON.stringify(prompts, null, 2)} as const;
`;

  fs.writeFileSync(file, content, 'utf-8');
  console.log(`✅ Wrote generated prompts: ${file}`);
};

/**
 * Bundle Worker using esbuild
 */
const bundleWorker = async () => {
  ensureDir(outDir);
  const outfile = path.join(outDir, 'index.js');

  console.log('🔨 Bundling Cloudflare Worker...');

  await build({
    entryPoints: [path.join(root, 'workers', 'index.ts')],
    outfile,
    bundle: true,
    format: 'esm', // Cloudflare Workers use ES modules
    target: 'es2020',
    platform: 'browser', // Workers use browser APIs
    minify: false, // Keep readable for debugging (can enable for production)
    sourcemap: true,
    banner: {
      js: [
        `// AI Visibility Tracker - Cloudflare Worker`,
        `// Built: ${new Date().toISOString()}`,
        `// Source: workers/ | Config: geo-visibility-config.toml`,
        '',
      ].join('\n'),
    },
    external: [
      // These are Worker built-ins, don't bundle
      'node:*',
    ],
    logLevel: 'info',
  });

  console.log(`✅ Worker bundle created: ${outfile}`);
  console.log(`   Size: ${(fs.statSync(outfile).size / 1024).toFixed(2)} KB`);
};

/**
 * Main build process
 */
const run = async () => {
  console.log('🚀 Building Cloudflare Worker...\n');

  try {
    // Load config from TOML (single source of truth)
    const parsed = loadTomlConfig();
    console.log(`✅ Loaded config from: ${configPath}\n`);

    // Generate prompts file
    writeGeneratedPrompts(parsed);

    // Bundle Worker
    await bundleWorker();

    console.log('\n✅ Build complete!\n');
    console.log('Next steps:');
    console.log('  1. Test locally:  wrangler dev');
    console.log('  2. Deploy:        wrangler deploy');
    console.log('  3. Visit:         https://ai-visibility-by-gsc-export.franzai.com\n');
  } catch (error) {
    console.error('❌ build:worker failed:', error);
    process.exit(1);
  }
};

run();
